// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/(public)/faq.tsx";
import * as $1 from "./routes/(public)/features.tsx";
import * as $2 from "./routes/(public)/pricing.tsx";
import * as $3 from "./routes/(public)/privacy-policy.tsx";
import * as $4 from "./routes/(public)/terms-of-service.tsx";
import * as $5 from "./routes/_404.tsx";
import * as $6 from "./routes/_app.tsx";
import * as $7 from "./routes/_layout.tsx";
import * as $8 from "./routes/api/auth/login.ts";
import * as $9 from "./routes/api/auth/signout.ts";
import * as $10 from "./routes/api/events/create.ts";
import * as $11 from "./routes/api/events/delete.ts";
import * as $12 from "./routes/api/events/edit.ts";
import * as $13 from "./routes/api/events/image/fill.ts";
import * as $14 from "./routes/api/events/image/upload.ts";
import * as $15 from "./routes/api/events/team/invite.ts";
import * as $16 from "./routes/api/events/team/remove.ts";
import * as $17 from "./routes/api/events/team/update.ts";
import * as $18 from "./routes/api/events/ticket.ts";
import * as $19 from "./routes/events/(pages)/_layout.tsx";
import * as $20 from "./routes/events/(pages)/attending/_layout.tsx";
import * as $21 from "./routes/events/(pages)/attending/index.tsx";
import * as $22 from "./routes/events/(pages)/organizing/_layout.tsx";
import * as $23 from "./routes/events/(pages)/organizing/accounting.tsx";
import * as $24 from "./routes/events/(pages)/organizing/collections.tsx";
import * as $25 from "./routes/events/(pages)/organizing/create.tsx";
import * as $26 from "./routes/events/(pages)/organizing/discounts.tsx";
import * as $27 from "./routes/events/(pages)/organizing/index.tsx";
import * as $28 from "./routes/events/[id]/(no-layout)/_layout.tsx";
import * as $29 from "./routes/events/[id]/(no-layout)/index.tsx";
import * as $30 from "./routes/events/[id]/(no-layout)/tickets/[tixid].tsx";
import * as $31 from "./routes/events/[id]/_layout.tsx";
import * as $32 from "./routes/events/[id]/editing.tsx";
import * as $33 from "./routes/events/[id]/scanning.tsx";
import * as $34 from "./routes/events/[id]/team.tsx";
import * as $35 from "./routes/events/[id]/tickets.tsx";
import * as $36 from "./routes/events/notfound.tsx";
import * as $37 from "./routes/index.tsx";
import * as $38 from "./routes/kv-insights/_layout.tsx";
import * as $39 from "./routes/kv-insights/_middleware.ts";
import * as $40 from "./routes/login.tsx";
import * as $$0 from "./islands/components/dropinUI/trash.tsx";
import * as $$1 from "./islands/components/peices/ticket.tsx";
import * as $$2 from "./islands/components/pickers/calender.tsx";
import * as $$3 from "./islands/components/pickers/dropdown.tsx";
import * as $$4 from "./islands/components/pickers/image.tsx";
import * as $$5 from "./islands/components/pickers/select.tsx";
import * as $$6 from "./islands/components/pickers/time.tsx";
import * as $$7 from "./islands/entriesManagement.tsx";
import * as $$8 from "./islands/entryManagement.tsx";
import * as $$9 from "./islands/events/components/card.tsx";
import * as $$10 from "./islands/events/creation/createForm.tsx";
import * as $$11 from "./islands/events/creation/one.tsx";
import * as $$12 from "./islands/events/creation/three.tsx";
import * as $$13 from "./islands/events/creation/two.tsx";
import * as $$14 from "./islands/events/creation/zero.tsx";
import * as $$15 from "./islands/events/editing/delete.tsx";
import * as $$16 from "./islands/events/editing/images.tsx";
import * as $$17 from "./islands/events/editing/settings.tsx";
import * as $$18 from "./islands/events/editing/showtimesettings.tsx";
import * as $$19 from "./islands/events/editing/ticketSettings.tsx";
import * as $$20 from "./islands/events/list/filters.tsx";
import * as $$21 from "./islands/events/scanning.tsx";
import * as $$22 from "./islands/events/teams/invite.tsx";
import * as $$23 from "./islands/events/teams/manage.tsx";
import * as $$24 from "./islands/events/viewing/availability.tsx";
import * as $$25 from "./islands/events/viewing/register.tsx";
import * as $$26 from "./islands/events/viewing/showtimes.tsx";
import * as $$27 from "./islands/loginForm.tsx";
import * as $$28 from "./islands/queueManagement.tsx";

const manifest = {
  routes: {
    "./routes/(public)/faq.tsx": $0,
    "./routes/(public)/features.tsx": $1,
    "./routes/(public)/pricing.tsx": $2,
    "./routes/(public)/privacy-policy.tsx": $3,
    "./routes/(public)/terms-of-service.tsx": $4,
    "./routes/_404.tsx": $5,
    "./routes/_app.tsx": $6,
    "./routes/_layout.tsx": $7,
    "./routes/api/auth/login.ts": $8,
    "./routes/api/auth/signout.ts": $9,
    "./routes/api/events/create.ts": $10,
    "./routes/api/events/delete.ts": $11,
    "./routes/api/events/edit.ts": $12,
    "./routes/api/events/image/fill.ts": $13,
    "./routes/api/events/image/upload.ts": $14,
    "./routes/api/events/team/invite.ts": $15,
    "./routes/api/events/team/remove.ts": $16,
    "./routes/api/events/team/update.ts": $17,
    "./routes/api/events/ticket.ts": $18,
    "./routes/events/(pages)/_layout.tsx": $19,
    "./routes/events/(pages)/attending/_layout.tsx": $20,
    "./routes/events/(pages)/attending/index.tsx": $21,
    "./routes/events/(pages)/organizing/_layout.tsx": $22,
    "./routes/events/(pages)/organizing/accounting.tsx": $23,
    "./routes/events/(pages)/organizing/collections.tsx": $24,
    "./routes/events/(pages)/organizing/create.tsx": $25,
    "./routes/events/(pages)/organizing/discounts.tsx": $26,
    "./routes/events/(pages)/organizing/index.tsx": $27,
    "./routes/events/[id]/(no-layout)/_layout.tsx": $28,
    "./routes/events/[id]/(no-layout)/index.tsx": $29,
    "./routes/events/[id]/(no-layout)/tickets/[tixid].tsx": $30,
    "./routes/events/[id]/_layout.tsx": $31,
    "./routes/events/[id]/editing.tsx": $32,
    "./routes/events/[id]/scanning.tsx": $33,
    "./routes/events/[id]/team.tsx": $34,
    "./routes/events/[id]/tickets.tsx": $35,
    "./routes/events/notfound.tsx": $36,
    "./routes/index.tsx": $37,
    "./routes/kv-insights/_layout.tsx": $38,
    "./routes/kv-insights/_middleware.ts": $39,
    "./routes/login.tsx": $40,
  },
  islands: {
    "./islands/components/dropinUI/trash.tsx": $$0,
    "./islands/components/peices/ticket.tsx": $$1,
    "./islands/components/pickers/calender.tsx": $$2,
    "./islands/components/pickers/dropdown.tsx": $$3,
    "./islands/components/pickers/image.tsx": $$4,
    "./islands/components/pickers/select.tsx": $$5,
    "./islands/components/pickers/time.tsx": $$6,
    "./islands/entriesManagement.tsx": $$7,
    "./islands/entryManagement.tsx": $$8,
    "./islands/events/components/card.tsx": $$9,
    "./islands/events/creation/createForm.tsx": $$10,
    "./islands/events/creation/one.tsx": $$11,
    "./islands/events/creation/three.tsx": $$12,
    "./islands/events/creation/two.tsx": $$13,
    "./islands/events/creation/zero.tsx": $$14,
    "./islands/events/editing/delete.tsx": $$15,
    "./islands/events/editing/images.tsx": $$16,
    "./islands/events/editing/settings.tsx": $$17,
    "./islands/events/editing/showtimesettings.tsx": $$18,
    "./islands/events/editing/ticketSettings.tsx": $$19,
    "./islands/events/list/filters.tsx": $$20,
    "./islands/events/scanning.tsx": $$21,
    "./islands/events/teams/invite.tsx": $$22,
    "./islands/events/teams/manage.tsx": $$23,
    "./islands/events/viewing/availability.tsx": $$24,
    "./islands/events/viewing/register.tsx": $$25,
    "./islands/events/viewing/showtimes.tsx": $$26,
    "./islands/loginForm.tsx": $$27,
    "./islands/queueManagement.tsx": $$28,
  },
  baseUrl: import.meta.url,
};

export default manifest;
